addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "1.0.6")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"               % "1.0.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"               % "0.9.3")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"           % "0.6.25")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"       % "0.1.17")
