addSbtPlugin("com.github.gseitz" % "sbt-release"            % "1.0.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"                % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"                % "0.8.4")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"            % "0.6.4")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin"        % "0.1.7")
